export default {
"login": "coderasraf",
"id": 57615868,
"node_id": "MDQ6VXNlcjU3NjE1ODY4",
"avatar_url": "https://avatars.githubusercontent.com/u/57615868?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/coderasraf",
"html_url": "https://github.com/coderasraf",
"followers_url": "https://api.github.com/users/coderasraf/followers",
"following_url": "https://api.github.com/users/coderasraf/following{/other_user}",
"gists_url": "https://api.github.com/users/coderasraf/gists{/gist_id}",
"starred_url": "https://api.github.com/users/coderasraf/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/coderasraf/subscriptions",
"organizations_url": "https://api.github.com/users/coderasraf/orgs",
"repos_url": "https://api.github.com/users/coderasraf/repos",
"events_url": "https://api.github.com/users/coderasraf/events{/privacy}",
"received_events_url": "https://api.github.com/users/coderasraf/received_events",
"type": "User",
"site_admin": false,
"name": "Hass Ashraf",
"company": "Codeboss.inc",
"blog": "https://www.linkedin.com/in/hass-ashraf-65765819a",
"location": "Sylhet, Bangladesh",
"email": null,
"hireable": true,
"bio": "I am a professional web designer and developer. I like to develop and design modern websites and also like sharing this little knowledge with other people.",
"twitter_username": "HassAsraf",
"public_repos": 58,
"public_gists": 0,
"followers": 1,
"following": 5,
"created_at": "2019-11-11T07:41:51Z",
"updated_at": "2022-05-11T07:15:15Z"
}
